import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core"

export const categories = sqliteTable("categories", {
  id: integer().primaryKey(),
  name: text().notNull(),
  slug: text().notNull(),
  href: text().notNull().default(""),
  gender: text().notNull(),
  parentId: integer("parent_id"),
  order: integer().default(0),
  image: text(),
  kind: text().notNull().default("category"),
  nav: integer().default(0),
  navOrder: integer("nav_order").default(0),
  visible: integer().default(1),
  imageSp: text("image_sp"),
  imagePc: text("image_pc"),
  videoUrl: text("video_url"),
  videoPoster: text("video_poster"),
  subtitle: text(),
  productCount: integer("product_count"),
})

export const products = sqliteTable("products", {
  id: integer().primaryKey({ autoIncrement: true }),
  productId: text("product_id").notNull().unique(),
  name: text().notNull(),
  description: text(),
  brand: text().default("UNIQLO"),
  section: text(),
  category: text(),
  subcategory: text(),
  price: integer(),
  rating: text(),
  reviewCount: integer("review_count"),
  gender: text().notNull(),
  categoryId: integer("category_id").references(() => categories.id),
  material: text(),
  colors: text().default("[]"),
  colorChips: text("color_chips").default("[]"),
  sizes: text().default("[]"),
  variants: text().default("[]"),
  gallery: text().default("[]"),
  aiReview: text("ai_review"),
  productDescription: text("product_description").default("[]"),
  inStock: integer("in_stock").default(1),
})

export const users = sqliteTable("users", {
  id: integer().primaryKey({ autoIncrement: true }),
  name: text().notNull(),
  email: text(),
  avatar: text(),
  provider: text().notNull(),
  providerId: text("provider_id").notNull(),
  role: text().default("user").notNull(),
  passwordHash: text("password_hash"),
  createdAt: text("created_at").notNull(),
})
